@startuml

title Buying a call
participant Alice
participant HegicOptions
participant PriceCalculator
participant PriceProvider
participant HegicPool
participant HegicRewards
participant HegicStaking


Alice --> HegicOptions: createFor
HegicOptions --> PriceCalculator: fees
PriceCalculator --> PriceProvider: latestRoundData
PriceCalculator <-- PriceProvider
PriceCalculator --> HegicOptions

HegicOptions --> HegicPool: lock
Alice <-- HegicOptions: safeTransferFrom
Alice --> HegicOptions: settlementFee + premium
HegicOptions --> HegicStaking: sendProfit
HegicOptions --> Alice: _safeMint (ERC721)

@enduml